name: workflow
on:
  workflow_dispatch

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v2
          with:
              username: yogendrapratap
              password: Naitik@29
        - name: Pull Image
          run: docker pull yogendrapratap/foodapp:1.0

        - name: Run Image
          run: docker run -d -p 8099:8080 yogendrapratap/sample-app-image:1.0
