name: workflow
on:
  workflow_dispatch

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - name: Docker Login
          uses: docker/login-action@v2
          with:
              username: yogendrapratap
              password: Naitik@29
        - name: Pull Image
          run: docker pull yogendrapratap/foodapp:1.0

        - name: Set Up Minikube (Local Testing)
          run: |
            minikube start
            kubectl config use-context minikube

        - name: Deploy to Minikube
          run: |
            kubectl apply -f k8s/deployment.yml
            kubectl apply -f k8s/service.yml

